name: "AquareaServiceCloud2MQTTHA"
version: "1.0.2"
slug: "aquareaservicecloud2mqqtha"
description: "Panasonic Aquarea Service Cloud to MQTT gateway (Python port)"
url: "https://github.com/bapver/AquareaServiceCloud2MQTTHA"
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: application
boot: auto
init: false
options:
  AquareaServiceCloudURL: "https://aquarea-service.panasonic.com/"
  AquareaServiceCloudLogin: ""
  AquareaServiceCloudPassword: ""
  AquareaTimeout: "30"
  PoolInterval: "60"
  LogSecOffset: 3600
  MqttServer: ""
  MqttPort: 1883
  MqttLogin: ""
  MqttPass: ""
  MqttClientID: "aquarea"
  MqttKeepalive: "60"
  LogLevel: "INFO"
  Language: "en"
schema:
  AquareaServiceCloudURL: str
  AquareaServiceCloudLogin: str
  AquareaServiceCloudPassword: str
  AquareaTimeout: str
  PoolInterval: str
  LogSecOffset: int
  MqttServer: str
  MqttPort: int
  MqttLogin: str
  MqttPass: str
  MqttClientID: str
  MqttKeepalive: str
  LogLevel: str
  Language: str
